In [1]:
import pandas as pd
import numpy as np

In [2]:
dt1 = pd.read_csv('99acres-gurgaon.csv')
dt2 = pd.read_csv('dt.csv')

In [3]:
dt1.head()

,Unnamed: 0,propertName,links,rating
0,0,"2 BHK Flatin Sector 3, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN
1,1,"3 BHK Flatin Sector 86, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.0
2,2,"3 BHK Flatin Nirvana Country, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.8
3,3,"2 BHK Flatin Sector 108, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,3.7
4,4,"3 BHK Flatin Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.1

In [4]:
dt1 = dt1.drop(columns = 'Unnamed: 0')

In [5]:
dt1 = dt1[~dt1['links'].duplicated(keep = 'first')] # removing the duplicate data

In [6]:
dt1.duplicated().sum()

0

In [7]:
dt2.head()

,Unnamed: 0,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,propertyId,links
0,0,in Godrej Habitat,1.32 Crore,NaN,1444.0,2 Bedrooms,2 Bathrooms,Servant Room,"Godrej Habitat\nSector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",E68327112,https://www.99acres.com/2-bhk-bedroom-apartmen...
1,1,in DLF The Skycourt,2.25 Crore,1929.0,1550.0,3 Bedrooms,3 Bathrooms,NaN,"DLF The Skycourt\nSector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",K79689999,https://www.99acres.com/3-bhk-bedroom-apartmen...
2,2,in Unitech Fresco,2.85 Crore,1877.0,1800.0,3 Bedrooms,4 Bathrooms,Servant Room,"Unitech Fresco\nNirvana Country, Gurgaon",9th of 19 Floors,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...",3 bhk with sq ready to move in luxury \nApartm...,"['3 Wardrobe', '7 Fan', '1 Fridge', '4 Geyser'...","['Water purifier', 'Security / Fire Alarm', 'P...",F78852763,https://www.99acres.com/3-bhk-bedroom-apartmen...
3,3,in Sobha City,2.65 Crore,1381.0,848.2,2 Bedrooms,2 Bathrooms,NaN,"Sobha City\nSector 108, Gurgaon",2nd of 24 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","Situated in sector 108 gurgaon, sobha city is ...","['2 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...",B79928269,https://www.99acres.com/2-bhk-bedroom-apartmen...
4,4,in Mapsko Mount Ville,2 Crore,1490.0,NaN,3 Bedrooms,3 Bathrooms,NaN,"Mapsko Mount Ville\nSector 79, Gurgaon",16th of 30 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This 3 bhk flat is located in mapsko mount vil...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '8 Li...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",D79959105,https://www.99acres.com/3-bhk-bedroom-apartmen...

In [8]:
dt2 = dt2.drop(columns = 'Unnamed: 0')

In [9]:
dt2.head()

,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,propertyId,links
0,in Godrej Habitat,1.32 Crore,NaN,1444.0,2 Bedrooms,2 Bathrooms,Servant Room,"Godrej Habitat\nSector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",E68327112,https://www.99acres.com/2-bhk-bedroom-apartmen...
1,in DLF The Skycourt,2.25 Crore,1929.0,1550.0,3 Bedrooms,3 Bathrooms,NaN,"DLF The Skycourt\nSector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",K79689999,https://www.99acres.com/3-bhk-bedroom-apartmen...
2,in Unitech Fresco,2.85 Crore,1877.0,1800.0,3 Bedrooms,4 Bathrooms,Servant Room,"Unitech Fresco\nNirvana Country, Gurgaon",9th of 19 Floors,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...",3 bhk with sq ready to move in luxury \nApartm...,"['3 Wardrobe', '7 Fan', '1 Fridge', '4 Geyser'...","['Water purifier', 'Security / Fire Alarm', 'P...",F78852763,https://www.99acres.com/3-bhk-bedroom-apartmen...
3,in Sobha City,2.65 Crore,1381.0,848.2,2 Bedrooms,2 Bathrooms,NaN,"Sobha City\nSector 108, Gurgaon",2nd of 24 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","Situated in sector 108 gurgaon, sobha city is ...","['2 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...",B79928269,https://www.99acres.com/2-bhk-bedroom-apartmen...
4,in Mapsko Mount Ville,2 Crore,1490.0,NaN,3 Bedrooms,3 Bathrooms,NaN,"Mapsko Mount Ville\nSector 79, Gurgaon",16th of 30 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This 3 bhk flat is located in mapsko mount vil...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '8 Li...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",D79959105,https://www.99acres.com/3-bhk-bedroom-apartmen...

In [10]:
dt2.duplicated().sum()

177

In [11]:
dt2 = dt2[~dt2.duplicated(keep  = 'first')]

In [12]:
dt2.duplicated().sum()

0

In [13]:
dt = dt1.merge(dt2 , on = 'links' , how = 'left') #merging the dataframes on the link as index

In [14]:
dt

,propertName,links,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,propertyId
0,"2 BHK Flatin Sector 3, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,in Godrej Habitat,1.32 Crore,NaN,1444.00,2 Bedrooms,2 Bathrooms,Servant Room,"Godrej Habitat\nSector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",E68327112
1,"3 BHK Flatin Sector 86, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.0,in DLF The Skycourt,2.25 Crore,1929.0,1550.00,3 Bedrooms,3 Bathrooms,NaN,"DLF The Skycourt\nSector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",K79689999
2,"3 BHK Flatin Nirvana Country, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.8,in Unitech Fresco,2.85 Crore,1877.0,1800.00,3 Bedrooms,4 Bathrooms,Servant Room,"Unitech Fresco\nNirvana Country, Gurgaon",9th of 19 Floors,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...",3 bhk with sq ready to move in luxury \nApartm...,"['3 Wardrobe', '7 Fan', '1 Fridge', '4 Geyser'...","['Water purifier', 'Security / Fire Alarm', 'P...",F78852763
3,"2 BHK Flatin Sector 108, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,3.7,in Sobha City,2.65 Crore,1381.0,848.20,2 Bedrooms,2 Bathrooms,NaN,"Sobha City\nSector 108, Gurgaon",2nd of 24 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","Situated in sector 108 gurgaon, sobha city is ...","['2 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...",B79928269
4,"3 BHK Flatin Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.1,in Mapsko Mount Ville,2 Crore,1490.0,NaN,3 Bedrooms,3 Bathrooms,NaN,"Mapsko Mount Ville\nSector 79, Gurgaon",16th of 30 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This 3 bhk flat is located in mapsko mount vil...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '8 Li...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",D79959105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2246,"3 BHK Flatin Sector 112, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.0,in Experion Windchants,4.7 Crore,2802.0,2225.56,3 Bedrooms,3 Bathrooms,Pooja Room,"Experion Windchants\nSector 112, Gurgaon",10th of 28 Floors,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Experion windchants is one of the most popular...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Centrally Air Conditioned'...",O76171945
2247,"3 BHK Flatin Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.5,in Ramprastha Primera,1.55 Crore,1775.0,NaN,3 Bedrooms,3 Bathrooms,NaN,"Ramprastha Primera\nSector 37D, Gurgaon",8th of 22 Floors,South-East,1 to 5 Year Old,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",Located in the popular residential address of ...,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",NaN,P79023159
2248,"4 BHK Flatin Sector 102, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,3.9,in Shapoorji Pallonji Joyville Gurugram,2.9 Crore,2162.0,1348.00,4 Bedrooms,4 Bathrooms,NaN,Shapoorji Pallonji Joyville Gurugram\nSector 1...,8th of 26 Floors,North,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",This lovely 4 bhk apartment/flat in sector 102...,"['16 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",Z78599409
2249,"3 BHK Flatin Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.9,in Shapoorji Pallonji Joyville Gurugram,2.48 Crore,1852.0,1320.00,3 Bedrooms,3 Bathrooms,NaN,Shapoorji Pallonji Joyville Gurugram\nSector 1...,8th of 26 Floors,North,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Located in the popular residential address of ...,"['12 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",J78599343
2250,"3 BHK Flatin Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.9,in BPTP Park Generations,2.2 Crore,2200.0,1833.00,3 Bedrooms,3 Bathrooms,Pooja Room,"BPTP Park Generations\nSector 37D, Gurgaon",19th of 19 Floors,North,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', '...",Ready to move in flat in sector 37d gurgaon. C...,"['5 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'F...",A62501724

In [15]:
dt.head(2)

,propertName,links,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,propertyId
0,"2 BHK Flatin Sector 3, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,in Godrej Habitat,1.32 Crore,NaN,1444.0,2 Bedrooms,2 Bathrooms,Servant Room,"Godrej Habitat\nSector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",E68327112
1,"3 BHK Flatin Sector 86, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.0,in DLF The Skycourt,2.25 Crore,1929.0,1550.0,3 Bedrooms,3 Bathrooms,NaN,"DLF The Skycourt\nSector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",K79689999

In [16]:
dt['society'] = dt['society'].str.replace('in','')

In [17]:
dt['address'] = dt['address'].str.replace('\n',' ')

In [41]:
dt.to_csv('gurgaon-flats-raw.csv')