In [2]:
import pandas as pd
import numpy as np
import re # regular expression used to extract a sequence from string

In [3]:
pd.set_option('display.max.rows' , None)
pd.set_option('display.max.columns' , None)

In [4]:
dt = pd.read_csv('gurgaon-flats-raw.csv' )

In [5]:
dt = dt.drop(columns = 'Unnamed: 0')

In [6]:
# deleted the empty rows 
dt = dt[~dt['propertyId'].isna()]

In [7]:
# we reseted the index drop true replace the old index by new one 
dt = dt.reset_index(drop = True)

In [8]:
dt.sample(5)

,propertName,links,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,propertyId
1961,"4 BHK Flatin Sector 99, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,4.1,Pareena Express Heights,2.4 Crore,2880.0,NaN,4 Bedrooms,4 Bathrooms,Servant Room,"Pareena Express Heights Sector 99, Gurgaon",12nd of 14 Floors,South,1 to 5 Year Old,"['Ocus Medley', 'Dwarka Expy, Sector 88', 'Eur...",Pareena express heights is one of the most pop...,"['4 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Water purifier', 'Centrally Air Conditioned'...",A79805705
1943,"3 BHK Flatin Sector 108, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,3.7,Sobha City,4.9 Crore,2343.0,1650.0,3 Bedrooms,5 Bathrooms,Servant Room,"Sobha City Sector 108, Gurgaon",10th of 24 Floors,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","This 3 bhk flat is located in sobha city, whic...","['4 Geyser', 'No AC', 'No Bed', 'No Chimney', ...","['Power Back-up', 'Private Garden / Terrace', ...",O78597171
1674,"3 BHK Flatin Sector 85, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,4.1,SS The Leaf,2.72 Crore,2408.0,2300.0,3 Bedrooms,4 Bathrooms,Servant Room,"SS The Leaf Sector 85, Gurgaon",2nd of 26 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 3 bhk apartment/flat in sector 85 ...,"['5 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Centrally Air Conditioned'...",Y79276003
1600,"3 BHK Flatin Sector 99, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,Pareena The Elite Residences,1.7 Crore,1865.0,NaN,3 Bedrooms,3 Bathrooms,Study Room,"Pareena The Elite Residences Sector 99, Gurgaon",10th of 15 Floors,North,1 to 5 Year Old,"['Adarsh Public School', 'Aryan Hospital', 'IG...",This 3 bhk apartment is available for sale in ...,"['Centrally Air Conditioned', 'Water purifier'...",NaN,Z80719473
423,"2 BHK Flatin Sector 48, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,4.3,Central Park Resorts,3.85 Crore,1418.0,NaN,2 Bedrooms,2 Bathrooms,Store Room,"Central Park Resorts Sector 48, Gurgaon",10th of 17 Floors,East,5 to 10 Year Old,"['Huda Metro Station', 'Omaxe Celebration Mall...","2 bhk available for sale , middle floor , low ...","['1 Modular Kitchen', '2 AC', 'No Bed', 'No Ch...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",W79510671

In [9]:
dt.shape

(2149, 19)

In [10]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   propertName      2149 non-null   object
 1   links            2149 non-null   object
 2   rating           1879 non-null   float64
 3   society          2149 non-null   object
 4   price            2149 non-null   object
 5   area             1953 non-null   float64
 6   areaWithType     1376 non-null   float64
 7   bedRooms         2149 non-null   object
 8   bathRooms        2149 non-null   object
 9   additionalRooms  1667 non-null   object
 10  address          2149 non-null   object
 11  floorNum         2149 non-null   object
 12  facing           2085 non-null   object
 13  agePossesion     2149 non-null   object
 14  nearbyLocation   2143 non-null   object
 15  description      2149 non-null   object
 16  furnishDetails   2148 non-null   object
 17  features         1783 non-null   object
 18  propertyId       2149 non-null   object
dtypes: float64(3), object(16)
memory usage: 319.1+ KB

In [11]:
dt.duplicated().sum() # displays the duplicated values

0

In [12]:
dt.isnull().sum() # diplays the sum of null values

propertName          0
links                0
rating             270
society              0
price                0
area               196
areaWithType       773
bedRooms             0
bathRooms            0
additionalRooms    482
address              0
floorNum             0
facing              64
agePossesion         0
nearbyLocation       6
description          0
furnishDetails       1
features           366
propertyId           0
dtype: int64

In [13]:
# we dont need the links and propertyId columns as they are of no use
dt.drop(columns = ['links','propertyId'],inplace = True)

In [14]:
dt.head(2)

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features
0,"2 BHK Flatin Sector 3, Gurgaon",NaN,Godrej Habitat,1.32 Crore,NaN,1444.0,2 Bedrooms,2 Bathrooms,Servant Room,"Godrej Habitat Sector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,"3 BHK Flatin Sector 86, Gurgaon",4.0,DLF The Skycourt,2.25 Crore,1929.0,1550.0,3 Bedrooms,3 Bathrooms,NaN,"DLF The Skycourt Sector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'..."

In [15]:
dt['society'].value_counts()

society
M3M Heights                                     63
M3M Woodshire                                   57
Adani M2K Oyster Grande                         54
Sobha City                                      50
Shapoorji Pallonji Joyville Gurugram            46
Paras Dews                                      42
Tata Primanti                                   41
DLF The Ultima                                  41
M3M Golfestate                                  38
Experion Wdchants                               37
Ireo Skyon                                      36
Ireo The Corridors                              35
Bestech Park View Grand Spa                     34
Indiabulls Centrum Park                         34
Ramprastha The Edge Towers                      34
DLF The Skycourt                                32
Emaar MGF The Palm Drive                        32
ATS Triumph                                     31
Godrej Meridien                                 31
Conscient Elevate                               28
SS The Leaf                                     28
ATS Tourmale                                    26
Bestech Park View Ananda                        25
Emaar MGF Emerald Floors Premier                25
Unitech Fresco                                  25
Tulip Purple                                    24
Bestech Park View Sanskruti                     23
Puri Emerald Bay                                23
Ramprastha Primera                              23
Mapsko Mount Ville                              22
Godrej Habitat                                  21
DLF The Primus                                  21
Indiabulls Enigma                               21
Experion The Heartsong                          21
Emaar Gurgaon Greens                            21
ATS Kocoon                                      20
Pareena Express Heights                         20
Pareena Coban Residences                        19
Vatika Gurgaon 21                               18
Emaar Palm Gardens                              18
M3M Merl                                        18
Vatika The Seven Lamps                          17
ATS Marigold                                    17
Microtek Greenburg                              16
Pareena Mi Casa                                 16
DLF New Town Heights 1                          15
Pioneer Park                                    14
TARC Maceo                                      14
Puri Diplomatic Greens                          14
Antriksh Heights                                14
Tulip Yellow                                    13
Unitech Escape                                  13
Orchid Petals                                   13
Ireo Victory Valley                             13
M3M Skycity                                     13
Tata Gurgaon Gateway                            12
DLF Park Place                                  12
Unitech Harmony                                 11
DLF New Town Heights 2                          11
Ireo The Grand Arch                             11
Emaar Imperial Gardens                          11
Central Park Flower Valley Aqua Front Towers    11
Emaar Mgf Palm Terraces Select                  10
Central Park Resorts                            10
Parsvnath Exotica                               10
SBTL Caladium                                    9
Vipul Greens                                     9
Emaar MGF Emerald Estate                         9
BPTP Terra                                       9
Tulip Ivory                                      9
Ireo Uptown                                      9
Emaar Digihomes                                  9
Alpha Corp GurgaonOne 84                         9
Ashiana The Center Court                         9
Bestech Altura                                   9
SS The Coralwood                                 8
Tulip Violet                                     8
Sare Crescent Parc                               8
Umang Wter Hills                                 8
AIPL The Peaceful Homes                          8
Godrej Air                                       8
Imperia The Esfera                               8
Vatika City                                      8
AWHO Sispal Vihar                                8
Ashiana Anmol                                    7
Sare Homes                                       7
The Close South                                  7
Vipul Lavanya                                    7
Krisumi Waterfall Residences                     7
GPL Eden Heights                                 7
Signature The Roselia                            7
Shree Vardhman Victoria                          7
DLF Regency Park 2                               6
Bestech Park View Spa Next                       6
Brisk Lumbi Terrace Homes                        6
La Vida by Tata Housg                            6
Vatika Sovereign Park                            6
Emaar MGF Palm Hills                             6
Chtels Serenity                                  6
Emaar MGF The Enclave                            6
BPTP Freedom Park Life                           6
BPTP Mansions Park Prime                         5
Pyramid Urban Homes                              5
Mapsko Paradise                                  5
Spaze Privy AT4                                  5
SS Lden Floors                                   5
DLF The Belaire                                  5
M3M Soulitude                                    5
M3M The Mara                                     4
M3M Flora                                        4
Spaze Kalistaa                                   4
DLF New Town Heights                             4
AIPL Zen Residences                              4
Umang Monsoon Breeze                             4
Shree Vardhman Flora                             4
Birla Navya                                      4
Signature Global City                            4
Tulip Monsella                                   4
Conscient Heritage Max                           4
Conscient Heritage One                           4
DLF Wellgton Estate                              4
Emaar Palm Heights                               4
BPTP Park Prime                                  4
Eldeco Accolade                                  4
Godrej Oasis                                     4
Raheja Vedaanta                                  3
Emaar Emerald Hills                              3
Mahdra Aura                                      3
Mapsko Royale Ville                              3
DLF Regal Gardens                                3
Tulip White                                      3
Paras Irene                                      3
Bestech Park View City                           3
Silverglades The Melia                           3
Suncity Essel Towers                             3
Vatika Xpressions                                3
Cosmos Express 99                                3
Mahdra Lumare                                    3
The Close North                                  2
International City by SOBHA Phase 2              2
Ansal Housg Highland Park                        2
Satya The Hermitage                              2
Assotech Blith                                   2
DLF Regency Park 1                               2
M3M Latitude                                     2
ILD Grand                                        2
New Shivalik Apartments                          2
Ashiana Mulberry                                 2
Unitech The Residences                           2
DLF Belvedere Towers                             2
Emaar Palm Premier                               2
Pyramid Urban                                    2
Vatika Seven Elements                            2
Godrej Icon                                      2
Central Park 2 Bellevue                          2
Godrej Summit                                    2
Unitech Uniworld City                            2
Tashee Capital Gateway                           2
Kiran Residency                                  2
Samanvay Apartment                               2
CHD Avenue 71                                    2
DLF Express Greens                               2
Ambience Creacions                               2
La Lagune                                        2
M3M St Andrews                                   2
ROF Ananda                                       2
Central Park Flower Valley                       2
DLF The Icon                                     2
Spaze Privvy The Address                         2
Central Park Flower Valley The Room              2
Raisa Residency                                  2
Parsvnath Green Ville                            2
Suncity Vatsal Valley                            2
Signature Global Grand IVA                       2
DLF Hamilton Court                               1
Unitech The World Spa West                       1
Spaze Privy                                      1
Pareena The Elite Residences                     1
Godrej Meridien                                  1
Signature Global Synera                          1
GLS Arawali Homes                                1
Corona Optus                                     1
Mapsko Casa Bella                                1
DLF Park Heights                                 1
Malibu Towne                                     1
Ansal Sushant Shoppg Arcade                      1
Sri Kirti Apartments                             1
Raheja Vedas                                     1
Salcon The Verandas                              1
Sheeba Apartments                                1
Godrej Aria                                      1
Ansal                                            1
Sagavi Apartments                                1
M3M Ikonic                                       1
DLF The Pnacle                                   1
DLF The Crest                                    1
Orris Aster Court                                1
Aawas Buildg                                     1
DLF Garden City Floors                           1
Green Court                                      1
Orris Carnation Residency                        1
Godrej Frontier                                  1
Orris Aster Court Premier                        1
DLF The Magnolias                                1
Pioneer Urban Presidia                           1
Pyramid Elite                                    1
Ardee Palm Grove Heights                         1
ILD Greens                                       1
Pyramid Urban Homes 2                            1
Bestech Park View City 2                         1
Signature Andour Heights                         1
Cdot Apartment                                   1
Alaknanda Apartments                             1
Abhandan CGHS                                    1
Krrish Provence Estate                           1
Residency Grand                                  1
Sukhshanti Apartment                             1
Anant Raj Estates                                1
Godrej Nature Plus Serenity                      1
Ansal Harmony Homes                              1
DLF Carlton Estate                               1
DLF Beverly Park                                 1
Valley View Estate                               1
Suncity Sukriti                                  1
Unitech Uniworld Gardens                         1
Pioneer Araya                                    1
IRWO Westend Towers                              1
Smart World Gems                                 1
AVL 36 Gurgaon                                   1
HSIIDC Sidco Shivalik Apartments                 1
IMT View Society                                 1
Denso Haryana Housg Society                      1
Signature Global park                            1
telectual society                                1
Vatika Independent Floors                        1
M3M Escala                                       1
Silverglades The Ivy                             1
The Citizen                                      1
Ansal API Esencia                                1
Rwa vigyan vihar sector 56 Gurgaon               1
Bhagwanti Apartment                              1
M3M Polo Suites                                  1
Vatika Boulevard Residences and Heights          1
Block H                                          1
sushant lok phase 1                              1
Emaar Mgf Sky Terraces                           1
Ansal Estella                                    1
Signature Global City 92                         1
M3M Sierra 68                                    1
Signature Global Orchard Avenue                  1
Ramsons Kshitij                                  1
Sare Petioles                                    1
Amour 81A Venue                                  1
Unitech Heritage City                            1
M3M  Heights                                     1
Godrej 101                                       1
Paras Quartier                                   1
Sidhartha NCR One Phase 2                        1
MRG The Balcony                                  1
Prerna Society                                   1
SS Hibiscus                                      1
MSL Apartments                                   1
Intelligentsia Apartment                         1
Ansal Heights                                    1
SS Almeria                                       1
Ardee The Residency                              1
BPTP Amstoria                                    1
BPTP Park Generations                            1
Name: count, dtype: int64

In [16]:
dt['society'].value_counts().shape  # so there are 268 categories

(268,)

In [17]:
# convert all to the lowercase so that captial and smallcase society names are not treated as two different 
dt['society'] = dt['society'].str.lower()

In [18]:
dt.sample(2)

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features
2047,"2 BHK Flatin Sector 37D, Gurgaon",3.5,ramprastha the edge towers,1.05 Crore,1410.0,1050.0,2 Bedrooms,2 Bathrooms,NaN,"Ramprastha The Edge Towers Sector 37D, Gurgaon",15th of 19 Floors,North-East,0 to 1 Year Old,"['The Esplanade Mall', 'Dwarka Express', 'Euro...",Ready to move in 2 bhk spacious flat for sale....,"['1 Wardrobe', '4 Fan', '1 Geyser', '6 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2074,"3 BHK Flatin Sector 102, Gurgaon",3.9,adani m2k oyster grande,2.7 Crore,1898.0,NaN,3 Bedrooms,3 Bathrooms,Servant Room,"Adani M2K Oyster Grande Sector 102, Gurgaon",9th of 24 Floors,East,1 to 5 Year Old,"['The Esplanade Mall', 'Dwarka Express Highway...","Near to dwarka expressway, 100acre reserved gr...","['4 Wardrobe', '3 Fan', '1 Exhaust Fan', '9 Li...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [19]:
dt['price'].value_counts() # we need to convert the price in same units (some are in crore some in lakhs)

price
2.5 Crore      43
1.9 Crore      38
2 Crore        37
2.4 Crore      37
2.55 Crore     33
2.35 Crore     32
2.3 Crore      32
2.1 Crore      30
2.9 Crore      27
2.8 Crore      27
2.65 Crore     26
2.25 Crore     26
1.8 Crore      26
2.6 Crore      26
2.45 Crore     24
3.5 Crore      24
3.4 Crore      23
3.6 Crore      23
2.7 Crore      23
2.75 Crore     23
2.85 Crore     23
1.85 Crore     22
1.7 Crore      22
3.75 Crore     22
1.5 Crore      21
2.15 Crore     21
3.8 Crore      20
1.45 Crore     20
3.7 Crore      20
1.4 Crore      20
1.6 Crore      19
2.2 Crore      19
1.75 Crore     19
3.55 Crore     18
1.95 Crore     17
2.95 Crore     17
1.55 Crore     17
3.2 Crore      16
3.25 Crore     16
4.1 Crore      16
4.5 Crore      15
3.65 Crore     15
3 Crore        15
4.25 Crore     15
1.35 Crore     14
4.8 Crore      14
3.9 Crore      13
5.5 Crore      13
1.65 Crore     13
3.1 Crore      13
2.05 Crore     13
1.3 Crore      12
3.3 Crore      12
4.9 Crore      12
3.15 Crore     12
1.25 Crore     11
6.1 Crore      11
3.85 Crore     11
4 Crore        11
4.75 Crore     11
3.05 Crore     11
5.9 Crore      10
6 Crore        10
5.3 Crore      10
4.7 Crore       9
2.62 Crore      9
3.45 Crore      9
5 Crore         9
4.2 Crore       9
4.55 Crore      9
7.5 Crore       8
3.35 Crore      8
1.87 Crore      7
2.33 Crore      7
5.75 Crore      7
3.68 Crore      7
8 Crore         7
2.42 Crore      7
9 Crore         7
8.5 Crore       6
1.86 Crore      6
1.05 Crore      6
2.39 Crore      6
5.7 Crore       6
1.89 Crore      6
4.15 Crore      6
1.83 Crore      6
1.96 Crore      6
5.25 Crore      6
4.65 Crore      6
2.38 Crore      6
4.95 Crore      6
1.78 Crore      6
4.6 Crore       6
2.72 Crore      6
2.48 Crore      6
1.42 Crore      6
3.95 Crore      6
1.99 Crore      5
8.75 Crore      5
2.79 Crore      5
6.3 Crore       5
4.3 Crore       5
2.51 Crore      5
1.98 Crore      5
2.49 Crore      5
1.79 Crore      5
5.8 Crore       5
1.77 Crore      5
1.88 Crore      5
1.49 Crore      5
2.27 Crore      5
1.72 Crore      5
4.85 Crore      5
1.44 Crore      5
2.88 Crore      5
2.37 Crore      5
1.97 Crore      4
1.76 Crore      4
6.25 Crore      4
2.18 Crore      4
1.36 Crore      4
2.63 Crore      4
1.32 Crore      4
2.98 Crore      4
1.2 Crore       4
1.15 Crore      4
65 Lac          4
7 Crore         4
1.58 Crore      4
2.22 Crore      4
4.4 Crore       4
1.63 Crore      4
2.58 Crore      4
1.64 Crore      4
1.1 Crore       4
2.28 Crore      4
1.81 Crore      4
6.5 Crore       4
9.5 Crore       4
1.41 Crore      4
1.43 Crore      4
2.16 Crore      4
2.78 Crore      4
5.4 Crore       4
3.56 Crore      4
1.38 Crore      3
1.22 Crore      3
2.87 Crore      3
1.54 Crore      3
61 Lac          3
2.64 Crore      3
4.35 Crore      3
3.59 Crore      3
1.59 Crore      3
5.45 Crore      3
2.32 Crore      3
3.22 Crore      3
2.17 Crore      3
6.2 Crore       3
3.67 Crore      3
1.93 Crore      3
5.2 Crore       3
2.01 Crore      3
4.45 Crore      3
6.8 Crore       3
1.48 Crore      3
1.68 Crore      3
1.27 Crore      3
2.24 Crore      3
2.44 Crore      3
1.28 Crore      3
6.9 Crore       3
1.53 Crore      3
5.65 Crore      3
2.08 Crore      2
3.79 Crore      2
2.06 Crore      2
3.58 Crore      2
2.73 Crore      2
1.16 Crore      2
1.57 Crore      2
2.04 Crore      2
3.91 Crore      2
5.6 Crore       2
2.91 Crore      2
2.56 Crore      2
5.39 Crore      2
4.99 Crore      2
72 Lac          2
3.73 Crore      2
7.9 Crore       2
5.1 Crore       2
7.05 Crore      2
5.35 Crore      2
1.56 Crore      2
1.71 Crore      2
7.3 Crore       2
4.22 Crore      2
2.67 Crore      2
4.72 Crore      2
3.42 Crore      2
3.86 Crore      2
2.14 Crore      2
4.53 Crore      2
8.2 Crore       2
4.26 Crore      2
3.82 Crore      2
1.07 Crore      2
1.82 Crore      2
3.21 Crore      2
4.88 Crore      2
4.09 Crore      2
3.44 Crore      2
1.66 Crore      2
3.18 Crore      2
2.34 Crore      2
2.47 Crore      2
8.25 Crore      2
8.1 Crore       2
7.6 Crore       2
2.84 Crore      2
4.39 Crore      2
1.52 Crore      2
2.52 Crore      2
10.5 Crore      2
2.69 Crore      2
1.23 Crore      2
2.68 Crore      2
2.02 Crore      2
10 Crore        2
7.2 Crore       2
5.99 Crore      2
3.78 Crore      2
2.82 Crore      2
13 Crore        2
2.19 Crore      2
1.39 Crore      2
9.25 Crore      2
2.93 Crore      2
4.11 Crore      2
2.89 Crore      2
2.21 Crore      2
2.36 Crore      2
2.12 Crore      2
2.77 Crore      2
3.62 Crore      2
9.65 Crore      2
70 Lac          2
2.92 Crore      2
3.49 Crore      2
3.28 Crore      2
1.92 Crore      2
7.45 Crore      2
2.29 Crore      2
6.95 Crore      2
3.77 Crore      2
5.49 Crore      2
4.81 Crore      2
1.74 Crore      2
2.41 Crore      2
2.99 Crore      2
3.72 Crore      2
3.81 Crore      2
66 Lac          2
7.95 Crore      2
3.48 Crore      2
3.01 Crore      2
1.29 Crore      2
3.69 Crore      2
8.05 Crore      1
1.21 Crore      1
5.44 Crore      1
1.24 Crore      1
5.79 Crore      1
4.87 Crore      1
29.75 Lac       1
4.98 Crore      1
1.73 Crore      1
16 Crore        1
1.34 Crore      1
2.76 Crore      1
12.35 Crore     1
4.58 Crore      1
1.61 Crore      1
17 Crore        1
4.92 Crore      1
12.75 Crore     1
1.09 Crore      1
5.28 Crore      1
2.03 Crore      1
8.6 Crore       1
1.51 Crore      1
42 Crore        1
25.44 Crore     1
76 Lac          1
5.05 Crore      1
1.33 Crore      1
4.52 Crore      1
4.37 Crore      1
13.5 Crore      1
10.3 Crore      1
2.86 Crore      1
3.11 Crore      1
6.45 Crore      1
1.67 Crore      1
3.31 Crore      1
4.32 Crore      1
4.57 Crore      1
68 Lac          1
4.73 Crore      1
3.29 Crore      1
2.66 Crore      1
8.39 Crore      1
7.15 Crore      1
16.32 Crore     1
3.83 Crore      1
67 Lac          1
84 Lac          1
5.06 Crore      1
3.09 Crore      1
62 Lac          1
4.18 Crore      1
42.6 Lac        1
5.94 Crore      1
3.26 Crore      1
6.35 Crore      1
6.6 Crore       1
4.84 Crore      1
1.94 Crore      1
3.03 Crore      1
15.5 Crore      1
3.99 Crore      1
56 Lac          1
6.75 Crore      1
59 Lac          1
2.54 Crore      1
14.2 Crore      1
2.71 Crore      1
1.18 Crore      1
14.5 Crore      1
3.84 Crore      1
4.74 Crore      1
4.78 Crore      1
3.76 Crore      1
8.66 Crore      1
78 Lac          1
4.16 Crore      1
3.57 Crore      1
5.81 Crore      1
1.01 Crore      1
1.62 Crore      1
2.07 Crore      1
3.88 Crore      1
8.9 Crore       1
1 Crore         1
3.37 Crore      1
4.24 Crore      1
5.09 Crore      1
13.51 Crore     1
6.14 Crore      1
6.4 Crore       1
7.55 Crore      1
2.43 Crore      1
18 Crore        1
10.25 Crore     1
12 Crore        1
7.09 Crore      1
5.56 Crore      1
4.62 Crore      1
3.54 Crore      1
7.25 Crore      1
9.58 Crore      1
3.32 Crore      1
7.7 Crore       1
4.08 Crore      1
8.15 Crore      1
27.26 Crore     1
6.19 Crore      1
4.49 Crore      1
1.46 Crore      1
15.92 Crore     1
11.75 Crore     1
1.08 Crore      1
2.13 Crore      1
2.46 Crore      1
6.99 Crore      1
1.91 Crore      1
8.95 Crore      1
1.69 Crore      1
3.19 Crore      1
3.12 Crore      1
5.15 Crore      1
1.02 Crore      1
4.28 Crore      1
3.23 Crore      1
8.3 Crore       1
5.95 Crore      1
3.51 Crore      1
4.42 Crore      1
80 Lac          1
14.25 Crore     1
3.98 Crore      1
3.02 Crore      1
7.85 Crore      1
3.07 Crore      1
4.02 Crore      1
3.33 Crore      1
4.41 Crore      1
3.53 Crore      1
5.42 Crore      1
4.56 Crore      1
72.5 Lac        1
58.25 Lac       1
2.53 Crore      1
4.67 Crore      1
13.2 Crore      1
3.47 Crore      1
5.85 Crore      1
4.21 Crore      1
8.65 Crore      1
6.58 Crore      1
3.71 Crore      1
8.49 Crore      1
4.82 Crore      1
91 Lac          1
11.85 Crore     1
9.8 Crore       1
72.8 Lac        1
3.08 Crore      1
1.84 Crore      1
14 Crore        1
9.7 Crore       1
7.16 Crore      1
8.73 Crore      1
1.17 Crore      1
Name: count, dtype: int64

In [20]:
dt['price'] = dt['price'].str.replace('Crore','')

In [21]:
dt['price']

0           1.32
1           2.25
2           2.85
3           2.65
4              2
5           4.85
6           2.47
7            1.6
8           1.59
9            5.9
10           5.4
11          2.45
12           1.8
13          2.55
14          3.75
15          4.65
16          4.62
17           2.8
18          2.16
19          4.95
20          2.85
21           3.6
22             9
23          3.95
24          5.75
25           1.4
26          3.95
27           2.9
28          2.25
29          2.65
30          3.54
31           2.7
32             3
33           1.5
34          3.15
35           3.4
36           2.5
37          4.65
38           9.5
39          1.44
40          7.25
41          2.48
42          3.59
43          5.75
44          2.55
45           2.7
46          1.44
47          2.47
48           8.1
49          2.55
50          3.45
51          2.25
52          5.75
53          9.58
54          1.75
55          2.65
56           2.6
57          3.32
58           2.8
59             9
60           2.3
61           3.1
62          2.35
63          2.85
64           3.1
65          5.45
66           1.3
67          1.41
68          3.55
69          1.85
70           1.8
71          6.95
72           7.7
73           4.6
74           4.1
75          4.08
76          2.38
77          2.27
78          8.15
79          2.15
80          2.88
81          1.44
82          1.35
83           2.5
84          2.25
85           2.5
86          2.65
87          3.55
88          3.75
89            10
90             8
91          3.68
92           2.4
93          2.55
94           2.7
95          2.87
96          3.25
97          4.25
98          2.45
99           1.7
100          3.1
101          3.3
102         5.99
103         3.78
104        27.26
105            7
106         6.19
107          3.6
108         4.49
109         3.55
110         1.25
111         1.78
112          3.7
113         2.35
114         1.46
115         2.42
116         4.95
117          1.5
118         2.95
119            3
120         2.85
121          1.1
122         9.65
123          1.4
124          3.4
125            2
126        66 Lac
127         3.45
128         3.75
129        15.92
130          5.9
131         1.93
132          5.7
133         2.02
134          1.7
135         4.55
136          2.8
137         2.68
138          1.5
139          8.5
140          1.9
141         1.72
142          3.6
143          3.1
144         1.05
145         2.39
146            5
147         1.83
148         9.65
149        11.75
150         1.27
151         4.65
152         3.75
153         2.65
154         1.35
155          2.9
156         2.28
157         2.37
158            9
159         2.85
160         2.25
161          4.5
162         2.95
163         2.65
164          7.5
165         3.75
166         2.95
167         2.38
168         1.08
169         3.81
170          2.3
171         3.67
172         2.13
173         2.48
174         5.49
175         2.46
176         6.99
177         1.91
178         1.81
179         8.75
180          3.7
181          2.5
182          6.5
183         2.39
184         2.35
185         2.41
186         2.35
187         2.42
188         3.25
189         2.75
190          2.7
191         1.85
192          1.9
193         2.45
194         3.72
195         1.55
196         5.56
197          3.4
198          2.2
199         1.45
200         4.15
201          2.5
202         1.89
203         3.65
204         2.55
205          2.3
206         1.29
207         1.87
208          2.7
209         2.16
210         4.39
211         1.65
212         2.15
213          3.7
214          2.7
215         3.68
216         2.52
217         1.32
218         7.45
219         5.45
220          4.7
221         1.77
222         7.09
223          2.3
224         1.99
225          3.4
226         2.82
227          2.3
228         1.99
229         3.65
230         5.75
231         1.45
232         6.25
233         2.85
234          5.9
235         4.25
236         4.25
237         2.75
238           13
239           12
240         9.25
241        10.25
242         8.66
243         3.55
244        78 Lac
245         1.41
246         2.12
247        70 Lac
248          3.8
249         1.48
250          1.7
251         4.16
252         3.57
253          4.9
254         5.81
255         2.22
256         1.27
257            2
258         2.44
259         3.28
260         5.65
261         3.72
262         3.75
263         3.49
264          8.1
265         4.65
266          3.1
267         2.92
268          3.2
269          2.8
270         3.62
271         1.95
272         2.45
273         2.65
274          3.4
275         1.01
276         1.62
277            2
278         1.79
279         2.07
280          3.2
281          2.6
282         1.72
283         1.89
284         1.87
285            2
286         3.55
287         1.85
288         2.89
289         3.81
290          4.8
291         2.84
292          3.6
293         2.25
294          4.4
295         3.55
296         3.35
297          2.3
298          3.4
299            9
300            4
301          2.2
302         3.88
303         3.85
304         2.95
305         2.19
306          2.9
307         2.15
308         1.79
309         2.25
310         3.76
311         3.65
312          4.2
313          8.9
314         3.55
315         2.72
316          1.7
317         2.51
318          2.4
319          2.7
320          1.9
321          3.8
322         2.35
323            9
324         3.25
325         3.85
326         2.12
327         2.55
328         1.55
329          4.5
330         5.25
331          7.2
332         8.75
333          7.5
334         3.22
335         2.58
336         1.97
337          3.5
338         3.37
339         4.24
340          2.1
341            3
342          1.7
343         1.23
344         2.69
345          4.1
346         3.75
347         4.85
348         10.5
349         5.09
350         2.25
351         1.44
352         3.65
353         2.25
354          2.6
355         3.85
356         2.45
357          2.2
358          2.3
359         2.18
360          2.5
361         2.05
362         1.92
363         1.96
364         2.62
365         10.5
366         2.58
367         2.98
368        13.51
369            7
370         6.14
371          2.6
372          2.8
373          7.5
374         2.37
375          4.9
376         3.65
377          2.6
378         1.42
379          3.4
380         2.15
381         4.25
382          6.4
383         2.85
384         3.69
385          3.6
386         7.95
387         3.48
388         1.41
389          1.6
390         2.68
391          1.7
392         1.45
393        61 Lac
394         1.55
395         2.35
396         2.58
397          5.5
398          2.4
399          3.3
400          2.4
401         7.55
402         1.95
403         3.75
404         2.43
405          1.8
406          1.9
407         2.25
408            3
409            2
410         2.85
411          1.4
412         1.85
413         8.75
414         1.54
415          3.7
416          3.2
417         2.65
418            2
419         2.49
420          2.2
421         2.99
422            5
423         3.85
424          2.9
425          2.2
426          1.7
427           18
428         1.74
429         3.25
430          4.8
431          3.2
432         1.85
433         8.95
434          3.8
435         3.77
436          3.8
437          5.9
438          5.7
439            1
440          2.7
441         1.93
442         2.15
443         4.74
444         1.98
445          3.4
446         2.32
447          1.9
448          4.1
449         3.85
450         1.69
451         2.98
452         2.22
453         3.75
454         2.88
455         1.45
456         8.75
457         1.45
458            8
459          3.9
460          3.8
461          4.8
462         3.98
463         2.92
464         5.25
465         13.2
466            5
467          7.5
468          3.9
469         2.85
470         3.47
471         3.25
472          7.6
473            6
474          5.3
475          2.6
476         4.35
477          2.1
478         2.37
479          1.4
480         2.55
481         2.89
482         4.95
483         1.75
484          5.3
485         1.65
486         4.55
487         3.45
488          4.5
489         1.65
490          3.7
491         1.45
492          2.3
493         3.05
494          2.1
495         2.88
496         1.74
497         4.75
498            5
499         1.59
500         4.99
501         1.93
502         3.25
503         2.37
504            2
505         3.65
506         3.85
507          2.2
508          4.5
509         6.95
510          2.3
511         1.95
512         1.99
513         2.75
514          2.7
515          1.9
516         2.88
517         4.15
518         1.55
519          3.9
520          3.1
521          3.9
522          2.5
523         8.75
524         3.55
525          3.6
526          5.5
527         5.85
528         2.33
529          4.3
530          2.5
531         2.91
532          4.1
533         4.21
534          3.8
535         8.65
536         6.58
537          4.8
538            3
539          3.6
540          1.4
541         3.75
542         1.38
543         3.71
544         1.35
545          5.8
546         1.88
547         1.87
548         2.25
549         1.75
550         1.65
551         3.59
552          5.9
553          6.1
554          3.1
555          2.3
556         2.69
557          3.9
558            7
559         8.49
560          2.3
561         3.35
562          3.1
563         4.25
564         1.65
565         1.32
566          2.5
567         2.64
568         3.49
569         2.35
570          2.1
571          3.6
572          8.5
573          7.5
574         2.75
575         3.73
576         2.55
577          3.5
578          5.3
579          1.3
580          3.4
581          4.2
582        72 Lac
583          3.1
584          2.3
585          3.7
586          2.9
587          3.3
588          3.6
589            6
590         3.55
591         4.82
592          6.3
593            5
594         3.22
595          3.6
596          1.7
597         3.85
598         2.55
599         1.05
600         5.99
601         1.43
602         2.55
603            3
604            8
605          6.1
606          1.9
607         1.85
608         1.64
609          2.4
610        91 Lac
611          3.5
612         6.25
613          4.7
614          2.1
615          2.7
616          1.5
617          2.1
618         1.16
619         1.75
620         2.55
621         1.85
622            3
623          4.9
624          4.6
625            7
626         1.77
627          2.7
628         1.79
629         3.55
630         1.83
631        11.85
632          9.8
633         2.06
634         2.08
635      72.8 Lac
636         3.75
637         3.75
638         1.22
639         3.65
640          2.5
641          1.7
642         3.82
643          3.7
644          2.6
645         2.16
646          2.3
647         2.33
648         3.08
649         3.25
650          2.4
651         1.84
652         1.81
653         3.55
654          5.9
655         2.05
656          2.9
657         4.55
658         3.59
659          2.5
660         2.34
661         1.16
662            2
663         1.85
664         1.85
665          3.4
666          1.9
667         3.18
668          2.4
669         1.64
670         1.66
671         1.95
672         2.25
673         4.09
674          2.5
675          1.2
676          1.8
677          2.7
678         2.95
679         2.15
680         1.15
681            2
682          1.5
683          2.5
684          1.5
685          2.9
686          3.8
687          2.9
688         3.85
689         1.83
690          2.4
691          2.9
692         2.45
693            2
694         2.15
695            3
696         2.35
697          3.4
698          2.7
699          2.9
700          3.3
701          6.3
702          1.8
703         1.81
704         1.85
705         1.75
706         1.82
707         1.65
708           14
709         2.85
710         3.15
711            6
712          1.3
713         1.95
714         2.25
715         2.85
716          1.7
717          9.7
718           10
719          4.2
720         2.02
721         3.05
722         1.38
723          1.7
724            2
725         2.38
726         1.05
727         5.65
728            2
729         4.55
730          1.8
731         2.88
732         4.26
733          3.6
734         1.35
735          1.7
736         2.15
737         2.65
738          3.6
739          2.7
740          1.4
741         7.95
742         2.25
743          3.7
744        65 Lac
745         2.65
746         2.42
747          5.5
748          4.5
749         7.16
750         1.58
751         8.73
752         4.67
753         1.78
754         3.75
755          4.2
756         3.86
757         1.87
758         2.55
759         1.95
760          2.7
761          1.4
762         2.53
763         1.45
764         3.85
765          2.2
766         1.45
767         1.85
768         2.65
769         3.42
770          3.8
771         2.15
772          5.3
773          3.6
774         4.72
775         1.45
776          1.3
777          4.3
778         2.75
779         1.55
780          2.9
781          2.3
782          1.1
783         3.78
784         3.15
785         3.73
786         3.45
787         1.35
788         1.32
789         1.15
790          2.6
791         1.45
792         1.25
793          1.9
794         2.39
795         2.67
796         2.28
797         1.42
798         2.48
799         1.42
800            4
801          3.7
802          4.2
803         2.25
804         2.75
805         3.55
806            2
807         4.25
808          2.3
809         4.25
810          4.5
811          2.4
812         1.97
813          2.5
814          7.2
815         1.25
816         2.17
817          4.2
818         4.22
819          3.2
820         1.35
821          2.6
822         2.65
823         3.25
824            3
825            2
826         2.78
827          3.2
828         1.25
829         1.75
830            4
831          3.7
832     58.25 Lac
833         2.35
834          2.4
835          5.5
836         1.71
837         1.38
838          2.5
839         3.35
840         8.25
841          7.9
842         1.85
843         2.95
844          2.5
845          1.8
846          2.2
847         1.75
848         1.25
849         2.25
850         1.79
851         1.43
852         1.65
853          2.8
854      72.5 Lac
855          1.8
856          1.6
857         4.75
858         1.56
859         5.15
860          1.5
861          2.3
862         3.65
863         3.35
864          3.2
865         1.92
866          5.5
867         1.63
868          7.9
869         2.14
870          2.1
871         2.28
872          3.9
873         2.39
874         2.51
875         4.75
876          8.2
877          2.3
878         5.35
879         3.55
880          5.5
881          5.5
882         2.58
883         3.21
884         2.62
885          1.3
886          4.5
887         3.65
888         2.32
889          3.9
890          5.9
891          3.4
892          1.8
893          3.4
894         1.83
895          1.8
896         3.15
897         2.05
898         3.55
899         2.45
900         1.89
901         1.02
902         2.85
903         1.85
904         2.75
905         1.55
906          1.2
907          2.1
908         1.95
909         3.68
910          2.4
911            6
912          2.6
913         1.88
914         1.78
915         1.87
916         2.18
917         1.83
918          2.5
919         4.45
920         2.55
921         2.45
922          3.7
923          3.5
924          1.6
925          1.6
926          1.9
927         1.82
928          1.8
929          2.8
930          4.9
931          1.6
932         2.35
933          4.6
934         2.15
935         3.75
936         1.95
937          1.9
938         1.45
939          1.4
940          1.4
941          3.6
942          2.1
943         1.45
944         2.75
945          2.4
946         3.44
947          1.9
948         2.01
949         2.55
950          2.9
951          1.7
952        66 Lac
953          2.5
954         3.75
955         3.15
956          1.8
957          1.3
958          2.8
959         2.42
960         2.33
961         4.28
962          1.3
963         2.45
964          1.9
965         2.79
966         1.63
967         3.48
968            2
969          2.8
970          3.4
971         3.23
972          2.6
973         4.75
974          5.1
975          8.3
976         5.95
977          3.8
978          6.1
979         1.97
980          1.9
981          2.2
982            4
983          2.1
984         3.45
985         2.55
986          1.9
987         1.36
988         2.24
989          1.3
990          2.5
991          2.1
992         1.36
993         2.35
994         1.15
995          2.6
996          3.3
997          2.8
998         4.25
999         1.76
1000        3.55
1001        2.18
1002         1.4
1003        3.51
1004           4
1005        4.42
1006        2.05
1007         2.1
1008        1.75
1009         5.9
1010        4.55
1011         8.5
1012        1.96
1013         3.7
1014        4.25
1015         4.6
1016         1.6
1017        3.91
1018         3.4
1019         6.8
1020        4.15
1021        5.39
1022        3.56
1023         4.1
1024         2.9
1025           3
1026        2.75
1027        3.05
1028         2.9
1029        4.95
1030         3.2
1031        5.45
1032         1.5
1033        2.45
1034         2.8
1035        2.05
1036        1.35
1037        2.87
1038         2.4
1039        4.55
1040        1.35
1041        4.65
1042         3.2
1043         3.3
1044         3.5
1045       80 Lac
1046           8
1047        1.68
1048         1.9
1049        2.05
1050         2.4
1051         3.5
1052        1.22
1053        1.86
1054        1.85
1055         2.5
1056        2.28
1057        4.85
1058        2.25
1059        1.68
1060        2.25
1061         8.5
1062         6.8
1063         5.8
1064         6.2
1065         3.9
1066         5.3
1067         2.5
1068           3
1069        1.79
1070         2.2
1071        1.96
1072        2.85
1073        3.05
1074        2.01
1075         9.5
1076         8.5
1077        3.12
1078       14.25
1079         1.6
1080         1.6
1081         6.1
1082        3.79
1083        3.02
1084        2.99
1085        7.85
1086        3.07
1087         4.8
1088         4.3
1089        2.56
1090        2.55
1091         1.9
1092         3.4
1093        2.42
1094         4.4
1095        4.02
1096           4
1097        1.28
1098        1.53
1099        1.58
1100        2.78
1101        3.95
1102         2.8
1103         2.3
1104         4.4
1105        4.35
1106        3.33
1107        3.25
1108         2.8
1109        3.75
1110         3.8
1111        2.45
1112        5.49
1113           2
1114         3.7
1115         4.7
1116         3.5
1117        3.65
1118           4
1119        4.41
1120         4.9
1121         6.9
1122        3.65
1123         4.9
1124        3.53
1125        3.56
1126        4.95
1127        5.42
1128        4.56
1129        4.15
1130         4.6
1131        5.35
1132           5
1133         3.7
1134        2.65
1135         3.5
1136         2.4
1137         1.6
1138        1.95
1139        2.78
1140        2.79
1141        3.18
1142        3.19
1143         2.5
1144        4.78
1145        1.75
1146        2.25
1147        2.35
1148         1.4
1149         2.3
1150        1.85
1151        3.35
1152         1.8
1153         1.4
1154         7.6
1155        2.35
1156        2.33
1157        2.33
1158         5.9
1159         3.6
1160        2.85
1161        1.48
1162        2.06
1163        1.72
1164         2.4
1165         2.3
1166         2.5
1167        1.86
1168         5.7
1169        3.68
1170        3.62
1171         1.5
1172        4.25
1173         2.1
1174        2.73

In [22]:
def convert(val):
    if val.split(' ')[1] == 'Lac':
        x = float(val.split(' ')[0])
        x = x/100
        return round(x,2)
    else:
        return round(float(val),2)

In [23]:
dt['price'] = dt['price'].apply(convert)

In [24]:
dt.sample(2)

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features
1412,"4 BHK Flatin Sector 102, Gurgaon",3.9,shapoorji pallonji joyville gurugram,2.95,2162.0,1348.0,4 Bedrooms,4 Bathrooms,NaN,Shapoorji Pallonji Joyville Gurugram Sector 10...,12nd of 26 Floors,North-East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Looking for a 4 bhk property for sale in gurga...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Lift(s)', 'Water purifier', 'Centrally Air C..."
27,"3 BHK Flatin Sector 82A, Gurgaon",4.2,dlf the primus,2.90,NaN,1818.0,3 Bedrooms,3 Bathrooms,Store Room,"DLF The Primus Sector 82A, Gurgaon",15th of 32 Floors,South,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...","Situated in sector 82a gurgaon, dlf the primus...","['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Water purifier', 'Centrally Air Conditioned'..."

In [25]:
# created a new column of area per square feet

In [26]:
dt['pricePerSqft'] = round((dt['price']*10000000)/dt['area'],2)

In [27]:
# removing the Bedrooms and bathrooms and converting it to integer

In [28]:
dt['bedRooms'] = dt['bedRooms'].str.replace('Bedrooms','')
dt['bedRooms'] = dt['bedRooms'].str.replace('Bedroom','')
dt['bedRooms'] = dt['bedRooms'].astype(int)

In [29]:
dt['bathRooms'] = dt['bathRooms'].str.replace('Bathrooms','')
dt['bathRooms'] = dt['bathRooms'].str.replace('Bathroom','')
dt['bathRooms'] = dt['bathRooms'].astype(int)

In [30]:
dt.sample(2)

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,pricePerSqft
99,"3 BHK FlatinSector 82, Gurgaon",3.8,vatika independent floors,1.7,NaN,1500.0,3,3,NaN,"Vatika Independent Floors Sector 82, Gurgaon",1st of 2 Floors,North-West,5 to 10 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...","Semi furnished, park facing, corner unit with ...","['3 Wardrobe', '5 Fan', '2 Geyser', '8 Light',...","['Power Back-up', 'Intercom Facility', 'High C...",NaN
1403,"3 BHK Flatin Sector 83, Gurgaon",4.0,emaar palm gardens,2.6,1900.0,1248.0,3,4,"Study Room,Servant Room","Emaar Palm Gardens Sector 83, Gurgaon",2nd of 16 Floors,East,1 to 5 Year Old,"['Millennium City Centre Gurugram', 'Entertain...",Emaar palm gardens is one of gurgaon's most so...,"['3 Wardrobe', '1 Water Purifier', '3 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...",13684.21

In [31]:
dt['additionalRooms'].value_counts()

additionalRooms
Servant Room                                     815
Study Room                                       144
Pooja Room                                       108
Others                                           105
Study Room,Servant Room                           95
Store Room                                        68
Servant Room,Study Room                           44
Servant Room,Pooja Room                           41
Pooja Room,Servant Room                           40
Servant Room,Store Room                           27
Pooja Room,Study Room,Servant Room,Store Room     21
Servant Room,Others                               18
Pooja Room,Study Room,Servant Room                 8
Servant Room,Study Room,Pooja Room,Store Room      7
Study Room,Store Room                              7
Pooja Room,Study Room,Servant Room,Others          7
Pooja Room,Store Room,Study Room,Servant Room      6
Study Room,Pooja Room                              6
Study Room,Others                                  5
Servant Room,Pooja Room,Study Room,Others          5
Servant Room,Pooja Room,Study Room                 5
Servant Room,Study Room,Pooja Room                 4
Pooja Room,Others                                  4
Servant Room,Pooja Room,Store Room,Study Room      4
Pooja Room,Store Room                              4
Servant Room,Study Room,Store Room                 3
Pooja Room,Store Room,Servant Room                 3
Others,Servant Room                                3
Pooja Room,Servant Room,Study Room                 3
Store Room,Servant Room                            3
Pooja Room,Study Room,Store Room,Servant Room      3
Pooja Room,Study Room                              3
Pooja Room,Study Room,Others,Servant Room          2
Servant Room,Pooja Room,Study Room,Store Room      2
Others,Pooja Room                                  2
Study Room,Servant Room,Others                     2
Study Room,Pooja Room,Store Room,Servant Room      2
Pooja Room,Servant Room,Others,Study Room          2
Store Room,Study Room                              2
Servant Room,Store Room,Study Room                 2
Study Room,Servant Room,Store Room                 2
Study Room,Servant Room,Pooja Room                 2
Pooja Room,Servant Room,Store Room                 2
Pooja Room,Servant Room,Others                     2
Others,Study Room,Servant Room                     1
Others,Store Room                                  1
Study Room,Store Room,Servant Room,Pooja Room      1
Store Room,Pooja Room,Study Room                   1
Servant Room,Store Room,Study Room,Pooja Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Study Room,Pooja Room,Servant Room                 1
Servant Room,Study Room,Store Room,Pooja Room      1
Servant Room,Others,Study Room,Pooja Room          1
Study Room,Pooja Room,Others                       1
Pooja Room,Study Room,Others                       1
Servant Room,Study Room,Others                     1
Store Room,Servant Room,Pooja Room                 1
Study Room,Servant Room,Pooja Room,Others          1
Pooja Room,Servant Room,Store Room,Study Room      1
Store Room,Pooja Room                              1
Servant Room,Others,Pooja Room                     1
Servant Room,Pooja Room,Others,Study Room          1
Others,Servant Room,Pooja Room                     1
Servant Room,Others,Pooja Room,Study Room          1
Pooja Room,Servant Room,Study Room,Others          1
Store Room,Pooja Room,Study Room,Servant Room      1
Study Room,Others,Pooja Room                       1
Others,Study Room                                  1
Name: count, dtype: int64

In [32]:
dt['additionalRooms'] = dt['additionalRooms'].str.lower()

In [33]:
dt['additionalRooms'] = dt['additionalRooms'].fillna('not available')

In [34]:
dt.head()

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,pricePerSqft
0,"2 BHK Flatin Sector 3, Gurgaon",NaN,godrej habitat,1.32,NaN,1444.0,2,2,servant room,"Godrej Habitat Sector 3, Gurgaon",4th of 17 Floors,North,0 to 1 Year Old,"['Huda City Centre Metro Station', 'Star Mall'...",2bhk semi furnished appartment for sale in god...,"['3 Fan', '4 Light', '2 AC', '2 TV', 'No Bed',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN
1,"3 BHK Flatin Sector 86, Gurgaon",4.0,dlf the skycourt,2.25,1929.0,1550.0,3,3,not available,"DLF The Skycourt Sector 86, Gurgaon",11st of 19 Floors,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This beautiful 3 bhk flat in sector 86 gurgaon...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",11664.07
2,"3 BHK Flatin Nirvana Country, Gurgaon",3.8,unitech fresco,2.85,1877.0,1800.0,3,4,servant room,"Unitech Fresco Nirvana Country, Gurgaon",9th of 19 Floors,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...",3 bhk with sq ready to move in luxury \nApartm...,"['3 Wardrobe', '7 Fan', '1 Fridge', '4 Geyser'...","['Water purifier', 'Security / Fire Alarm', 'P...",15183.80
3,"2 BHK Flatin Sector 108, Gurgaon",3.7,sobha city,2.65,1381.0,848.2,2,2,not available,"Sobha City Sector 108, Gurgaon",2nd of 24 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'WTC Plaza'...","Situated in sector 108 gurgaon, sobha city is ...","['2 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Centrally Air Conditioned', 'Water purifier'...",19188.99
4,"3 BHK Flatin Sector 79, Gurgaon",4.1,mapsko mount ville,2.00,1490.0,NaN,3,3,not available,"Mapsko Mount Ville Sector 79, Gurgaon",16th of 30 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This 3 bhk flat is located in mapsko mount vil...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '8 Li...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",13422.82

In [35]:
dt['floorNum'].value_counts()

floorNum
7th   of 14 Floors       39
5th   of 14 Floors       35
8th   of 14 Floors       29
7th   of 19 Floors       28
8th   of 19 Floors       27
6th   of 14 Floors       27
10th   of 14 Floors      24
10th   of 19 Floors      23
11st   of 19 Floors      22
6th   of 19 Floors       18
12nd   of 14 Floors      17
9th   of 14 Floors       17
9th   of 19 Floors       17
6th   of 24 Floors       16
12nd   of 19 Floors      15
5th   of 19 Floors       15
15th   of 19 Floors      15
8th   of 18 Floors       14
12nd   of 24 Floors      14
4th   of 14 Floors       14
10th   of 18 Floors      14
5th   of 24 Floors       14
2nd   of 4 Floors        14
14th   of 14 Floors      14
6th   of 12 Floors       13
7th   of 13 Floors       13
8th   of 29 Floors       12
10th   of 24 Floors      12
3rd   of 18 Floors       12
5th   of 18 Floors       12
8th   of 17 Floors       12
9th   of 24 Floors       12
4th   of 19 Floors       11
10th   of 27 Floors      11
7th   of 17 Floors       11
6th   of 17 Floors       11
7th   of 24 Floors       11
10th   of 26 Floors      11
3rd   of 14 Floors       10
11st   of 24 Floors      10
8th   of 20 Floors       10
3rd   of 4 Floors        10
15th   of 34 Floors      10
7th   of 29 Floors       10
8th   of 12 Floors       10
7th   of 18 Floors       10
5th   of 13 Floors       10
5th   of 17 Floors        9
11st   of 21 Floors       9
14th   of 19 Floors       9
1st   of 4 Floors         9
3rd   of 12 Floors        9
10th   of 29 Floors       9
12nd   of 29 Floors       9
8th   of 24 Floors        9
3rd   of 17 Floors        8
8th   of 32 Floors        8
12nd   of 18 Floors       8
10th   of 13 Floors       8
10th   of 12 Floors       8
10th   of 15 Floors       8
8th   of 16 Floors        8
12nd   of 34 Floors       8
6th   of 18 Floors        8
15th   of 24 Floors       8
10th   of 16 Floors       8
15th   of 26 Floors       8
12nd   of 27 Floors       8
3rd   of 19 Floors        8
15th   of 29 Floors       8
11st   of 29 Floors       7
4th   of 24 Floors        7
5th   of 15 Floors        7
2nd   of 24 Floors        7
5th   of 40 Floors        7
8th   of 27 Floors        7
14th   of 24 Floors       7
2nd   of 5 Floors         7
12nd   of 20 Floors       7
2nd   of 13 Floors        7
16th   of 25 Floors       7
8th   of 15 Floors        7
7th   of 12 Floors        7
6th   of 21 Floors        7
3rd   of 13 Floors        7
8th   of 26 Floors        7
6th   of 22 Floors        7
2nd   of 19 Floors        7
10th   of 34 Floors       7
14th   of 20 Floors       7
9th   of 16 Floors        7
8th   of 21 Floors        7
20th   of 34 Floors       7
15th   of 18 Floors       7
9th   of 34 Floors        6
9th   of 26 Floors        6
14th   of 22 Floors       6
6th   of 16 Floors        6
14th   of 15 Floors       6
10th   of 22 Floors       6
16th   of 19 Floors       6
5th   of 12 Floors        6
15th   of 27 Floors       6
5th   of 22 Floors        6
4th   of 5 Floors         6
7th   of 15 Floors        6
7th   of 21 Floors        6
9th   of 22 Floors        6
11st   of 14 Floors       6
20th   of 40 Floors       6
18th   of 29 Floors       6
4th   of 12 Floors        6
3rd   of 26 Floors        6
12nd   of 35 Floors       6
9th   of 18 Floors        6
11st   of 16 Floors       6
10th   of 35 Floors       5
10th   of 23 Floors       5
6th   of 34 Floors        5
25th   of 40 Floors       5
2nd   of 14 Floors        5
2nd   of 26 Floors        5
7th   of 10 Floors        5
10th   of 20 Floors       5
7th   of 27 Floors        5
5th   of 26 Floors        5
1st   of 21 Floors        5
9th   of 12 Floors        5
14th   of 17 Floors       5
1st   of 14 Floors        5
3rd   of 21 Floors        5
11st   of 34 Floors       5
3rd   of 20 Floors        5
5th   of 29 Floors        5
10th   of 10 Floors       5
17th   of 19 Floors       5
4th   of 4 Floors         5
19th   of 19 Floors       5
16th   of 22 Floors       5
15th   of 40 Floors       5
12nd   of 25 Floors       5
16th   of 26 Floors       5
12nd   of 12 Floors       5
10th   of 17 Floors       5
15th   of 30 Floors       5
12nd   of 26 Floors       5
1st   of 19 Floors        5
6th   of 26 Floors        5
15th   of 32 Floors       5
17th   of 26 Floors       5
5th   of 21 Floors        5
12nd   of 17 Floors       5
8th   of 22 Floors        4
6th   of 32 Floors        4
24th   of 30 Floors       4
10th   of 28 Floors       4
3rd   of 24 Floors        4
Ground of 12 Floors       4
3rd   of 15 Floors        4
9th   of 13 Floors        4
4th   of 18 Floors        4
12nd   of 21 Floors       4
25th   of 34 Floors       4
1st   of 24 Floors        4
18th   of 34 Floors       4
14th   of 30 Floors       4
2nd   of 18 Floors        4
15th   of 22 Floors       4
11st   of 17 Floors       4
19th   of 29 Floors       4
Ground of 14 Floors       4
1st   of 17 Floors        4
9th   of 21 Floors        4
20th   of 26 Floors       4
2nd   of 34 Floors        4
9th   of 23 Floors        4
10th   of 21 Floors       4
6th   of 10 Floors        4
3rd   of 40 Floors        4
5th   of 16 Floors        4
7th   of 40 Floors        4
11st   of 18 Floors       4
16th   of 24 Floors       4
4th   of 15 Floors        4
25th   of 30 Floors       4
18th   of 22 Floors       4
4th   of 16 Floors        3
1st   of 3 Floors         3
10th   of 39 Floors       3
29th   of 34 Floors       3
4th   of 28 Floors        3
11st   of 40 Floors       3
8th   of 34 Floors        3
2nd   of 3 Floors         3
19th   of 40 Floors       3
6th   of 28 Floors        3
8th   of 39 Floors        3
8th   of 10 Floors        3
1st   of 34 Floors        3
17th   of 21 Floors       3
1st   of 5 Floors         3
18th   of 26 Floors       3
10th   of 32 Floors       3
16th   of 29 Floors       3
20th   of 27 Floors       3
14th   of 40 Floors       3
15th   of 17 Floors       3
18th   of 27 Floors       3
4th   of 11 Floors        3
27th   of 34 Floors       3
6th   of 13 Floors        3
10th   of 33 Floors       3
2nd   of 17 Floors        3
3rd   of 5 Floors         3
3rd   of 22 Floors        3
11st   of 23 Floors       3
9th   of 32 Floors        3
15th   of 20 Floors       3
18th   of 28 Floors       3
5th   of 9 Floors         3
14th   of 23 Floors       3
16th   of 40 Floors       3
19th   of 27 Floors       3
7th   of 34 Floors        3
6th   of 15 Floors        3
8th   of 13 Floors        3
5th   of 10 Floors        3
3rd   of 3 Floors         3
12nd   of 15 Floors       3
Ground of 19 Floors       3
19th   of 24 Floors       3
4th   of 29 Floors        3
6th   of 40 Floors        3
14th   of 21 Floors       3
12nd   of 22 Floors       3
11st   of 26 Floors       3
11st   of 22 Floors       3
Ground of 4 Floors        3
6th   of 20 Floors        3
7th   of 26 Floors        3
31st   of 34 Floors       3
20th   of 32 Floors       3
9th   of 27 Floors        3
9th   of 15 Floors        3
Ground of 21 Floors       3
2nd   of 16 Floors        3
15th   of 28 Floors       3
21st   of 28 Floors       3
15th   of 21 Floors       3
12nd   of 16 Floors       3
1st   of 2 Floors         3
2nd   of 23 Floors        3
Ground of 25 Floors       3
22nd   of 29 Floors       3
16th   of 34 Floors       3
7th   of 20 Floors        3
3rd   of 29 Floors        3
14th   of 27 Floors       3
8th   of 11 Floors        3
5th   of 20 Floors        3
2nd   of 9 Floors         3
18th   of 18 Floors       3
22nd   of 33 Floors       3
16th   of 33 Floors       3
5th   of 30 Floors        3
9th   of 17 Floors        2
6th   of 27 Floors        2
2nd   of 30 Floors        2
2nd   of 40 Floors        2
20th   of 30 Floors       2
1st   of 13 Floors        2
22nd   of 34 Floors       2
22nd   of 40 Floors       2
1st   of 33 Floors        2
19th   of 34 Floors       2
22nd   of 24 Floors       2
25th   of 29 Floors       2
21st   of 22 Floors       2
26th   of 26 Floors       2
19th   of 26 Floors       2
21st   of 24 Floors       2
5th   of 25 Floors        2
21st   of 30 Floors       2
21st   of 40 Floors       2
5th   of 11 Floors        2
14th   of 32 Floors       2
8th   of 30 Floors        2
20th   of 29 Floors       2
8th   of 40 Floors        2
6th   of 30 Floors        2
Ground of 18 Floors       2
22nd   of 26 Floors       2
5th   of 34 Floors        2
9th   of 20 Floors        2
13rd   of 24 Floors       2
3rd   of 7 Floors         2
10th   of 25 Floors       2
23rd   of 30 Floors       2
30th   of 34 Floors       2
15th   of 33 Floors       2
11st   of 33 Floors       2
4th   of 20 Floors        2
9th   of 11 Floors        2
16th   of 16 Floors       2
22nd   of 30 Floors       2
16th   of 18 Floors       2
11st   of 32 Floors       2
17th   of 23 Floors       2
11st   of 12 Floors       2
21st   of 29 Floors       2
28th   of 39 Floors       2
14th   of 25 Floors       2
20th   of 48 Floors       2
12nd   of 30 Floors       2
24th   of 32 Floors       2
17th   of 24 Floors       2
17th   of 18 Floors       2
19th   of 20 Floors       2
5th   of 23 Floors        2
7th   of 8 Floors         2
8th   of 33 Floors        2
3rd   of 32 Floors        2
3rd   of 8 Floors         2
14th   of 29 Floors       2
11st   of 27 Floors       2
11st   of 35 Floors       2
5th   of 8 Floors         2
5th   of 33 Floors        2
7th   of 16 Floors        2
1st   of 16 Floors        2
5th   of 7 Floors         2
4th   of 22 Floors        2
7th   of 32 Floors        2
20th   of 24 Floors       2
25th   of 25 Floors       2
2nd   of 20 Floors        2
7th   of 9 Floors         2
16th   of 20 Floors       2
11st   of 25 Floors       2
18th   of 24 Floors       2
18th   of 30 Floors       2
5th   of 51 Floors        2
7th   of 25 Floors        2
18th   of 33 Floors       2
7th   of 30 Floors        2
2nd   of 12 Floors        2
5th   of 28 Floors        2
11st   of 28 Floors       2
7th   of 11 Floors        2
12nd   of 13 Floors       2
33rd   of 34 Floors       2
3rd   of 28 Floors        2
3rd   of 30 Floors        2
13rd   of 18 Floors       2
16th   of 27 Floors       2
11st   of 11 Floors       2
4th   of 27 Floors        2
12nd   of 42 Floors       1
3rd   of 33 Floors        1
Ground of 17 Floors       1
8th   of 23 Floors        1
Ground of 29 Floors       1
23rd   of 32 Floors       1
1st   of 12 Floors        1
Ground of 11 Floors       1
9th   of 28 Floors        1
37th   of 42 Floors       1
17th   of 48 Floors       1
4th   of 34 Floors        1
14th   of 34 Floors       1
2nd   of 10 Floors        1
17th   of 29 Floors       1
Basement of 32 Floors     1
18th   of 19 Floors       1
4th   of 13 Floors        1
4th   of 23 Floors        1
22nd   of 32 Floors       1
13rd   of 26 Floors       1
24th   of 28 Floors       1
1st   of 22 Floors        1
4th   of 40 Floors        1
15th   of 35 Floors       1
11st   of 20 Floors       1
Ground of 40 Floors       1
9th   of 35 Floors        1
9th   of 25 Floors        1
5th   of 32 Floors        1
11st   of 15 Floors       1
29th   of 40 Floors       1
Ground of 26 Floors       1
13rd   of 14 Floors       1
9th   of 33 Floors        1
7th   of 28 Floors        1
Ground of 3 Floors        1
3rd   of 11 Floors        1
2nd   of 15 Floors        1
9th   of 10 Floors        1
17th   of 22 Floors       1
22nd   of 27 Floors       1
24th   of 33 Floors       1
19th   of 28 Floors       1
30th   of 32 Floors       1
14th   of 26 Floors       1
3rd   of 27 Floors        1
12nd   of 32 Floors       1
27th   of 30 Floors       1
35th   of 47 Floors       1
30th   of 48 Floors       1
23rd   of 47 Floors       1
38th   of 43 Floors       1
17th   of 20 Floors       1
19th   of 47 Floors       1
20th   of 47 Floors       1
23rd   of 29 Floors       1
10th   of 30 Floors       1
1st   of 9 Floors         1
11st   of 13 Floors       1
21st   of 21 Floors       1
29th   of 33 Floors       1
22nd   of 22 Floors       1
4th   of 26 Floors        1
9th   of 39 Floors        1
23rd   of 33 Floors       1
10th   of 40 Floors       1
25th   of 31 Floors       1
31st   of 32 Floors       1
20th   of 21 Floors       1
20th   of 35 Floors       1
24th   of 36 Floors       1
8th   of 47 Floors        1
20th   of 51 Floors       1
15th   of 15 Floors       1
22nd   of 47 Floors       1
27th   of 29 Floors       1
17th   of 35 Floors       1
Ground of 8 Floors        1
4th   of 17 Floors        1
20th   of 33 Floors       1
1st   of 6 Floors         1
13rd   of 25 Floors       1
21st   of 39 Floors       1
19th   of 25 Floors       1
32nd   of 39 Floors       1
20th   of 36 Floors       1
2nd   of 32 Floors        1
4th   of 25 Floors        1
35th   of 40 Floors       1
7th   of 22 Floors        1
16th   of 39 Floors       1
9th   of 29 Floors        1
2nd   of 27 Floors        1
11st   of 39 Floors       1
6th   of 11 Floors        1
3rd   of 6 Floors         1
13rd   of 13 Floors       1
2nd   of 22 Floors        1
17th   of 36 Floors       1
30th   of 30 Floors       1
12nd   of 23 Floors       1
4th   of 8 Floors         1
16th   of 32 Floors       1
18th   of 21 Floors       1
21st   of 47 Floors       1
15th   of 23 Floors       1
12nd   of 39 Floors       1
12nd   of 47 Floors       1
16th   of 30 Floors       1
17th   of 33 Floors       1
12nd   of 28 Floors       1
30th   of 47 Floors       1
13rd   of 29 Floors       1
13rd   of 28 Floors       1
3rd   of 10 Floors        1
1st   of 7 Floors         1
18th   of 36 Floors       1
18th   of 20 Floors       1
1st   of 30 Floors        1
20th   of 22 Floors       1
14th   of 18 Floors       1
17th   of 17 Floors       1
45   of 47 Floors         1
35th   of 36 Floors       1
20th   of 28 Floors       1
17th   of 25 Floors       1
17th   of 30 Floors       1
32nd   of 35 Floors       1
21st   of 33 Floors       1
16th   of 17 Floors       1
9th   of 30 Floors        1
23rd   of 34 Floors       1
12nd   of 40 Floors       1
20th   of 25 Floors       1
31st   of 47 Floors       1
Ground of 30 Floors       1
Ground of 20 Floors       1
36th   of 39 Floors       1
Ground of 2 Floors        1
8th   of 9 Floors         1
3rd   of 9 Floors         1
1st   of 26 Floors        1
6th   of 39 Floors        1
5th   of 5 Floors         1
31st   of 51 Floors       1
1st   of 18 Floors        1
24th   of 47 Floors       1
16th   of 28 Floors       1
3rd   of 31 Floors        1
6th   of 25 Floors        1
19th   of 21 Floors       1
3rd   of 43 Floors        1
11st   of 47 Floors       1
9th   of 40 Floors        1
25th   of 28 Floors       1
2nd   of 7 Floors         1
1st   of 20 Floors        1
4th   of 7 Floors         1
19th   of 22 Floors       1
Ground of 10 Floors       1
36th   of 51 Floors       1
19th   of 32 Floors       1
3rd   of 16 Floors        1
23rd   of 28 Floors       1
13rd   of 39 Floors       1
6th   of 6 Floors         1
4th   of 51 Floors        1
4th   of 21 Floors        1
32nd   of 47 Floors       1
9th   of 47 Floors        1
21st   of 27 Floors       1
7th   of 39 Floors        1
4th   of 9 Floors         1
17th   of 27 Floors       1
18th   of 25 Floors       1
16th   of 21 Floors       1
Ground of 15 Floors       1
15th   of 47 Floors       1
7th   of 7 Floors         1
3rd   of 34 Floors        1
24th   of 34 Floors       1
21st   of 32 Floors       1
25th   of 26 Floors       1
Name: count, dtype: int64

In [36]:
dt['floorNum'] = dt['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.replace('Basement','-1').str.strip().str.extract(r'(-?\d+)')

    used to extract the numerical vlaue from the the string 
        
        .str.extract(r'(-?\d+)')

In [38]:
dt['floorNum'] = dt['floorNum'].astype(int)

In [39]:
dt.sample()

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,pricePerSqft
1178,"3 BHK Flatin Sector 83, Gurgaon",4.0,emaar palm gardens,2.4,NaN,1720.0,3,3,servant room,"Emaar Palm Gardens Sector 83, Gurgaon",8,North,5 to 10 Year Old,"['Millennium City Centre Gurugram', 'Entertain...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Water purifier', 'Centrally Air Conditioned'...",NaN

In [40]:
dt['facing'] = dt['facing'].str.lower()

In [41]:
dt['facing'].fillna('na',inplace = True)

/var/folders/gy/lt_77nr13fs5zj9y4gdv7v4r0000gn/T/ipykernel_3605/1324546083.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt['facing'].fillna('na',inplace = True)

In [42]:
dt['facing'].value_counts()

facing
north-east    591
east          590
north         394
west          127
north-west    127
south         100
south-east     93
na             64
south-west     63
Name: count, dtype: int64

In [43]:
dt.sample(2)

,propertName,rating,society,price,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features,pricePerSqft
1192,"3 BHK Flatin Sector 84, Gurgaon",3.5,ss the coralwood,2.05,1890.0,NaN,3,3,not available,"SS The Coralwood Sector 84, Gurgaon",10,north,1 to 5 Year Old,"['Sapphire 83 Mall', 'Sector 84 Road', 'Dwarka...",Very nice location walking distance dwarka exp...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian...",10846.56
1844,"4 BHK Flatin Sector 86, Gurgaon",4.0,dlf new town heights 2,2.60,2364.0,2100.0,4,4,"pooja room,servant room","DLF New Town Heights 2 Sector 86, Gurgaon",14,east,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",Contact-991-050-1693 for more details or visit...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...",10998.31

In [44]:
# changin the position of a column 
temp = dt.pop('pricePerSqft')
dt.insert(4,'pricePerSqft',temp)

In [89]:
dt.sample(2)

,propertName,rating,society,price,pricePerSqft,area,areaWithType,bedRooms,bathRooms,additionalRooms,address,floorNum,facing,agePossesion,nearbyLocation,description,furnishDetails,features
1031,"3 BHK Flatin sector 58, Gurgaon",3.9,ireo the grand arch,5.45,22455.71,2427.0,1860.0,3,4,"study room,servant room","Ireo The Grand Arch sector 58, Gurgaon",16,north-west,5 to 10 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Best deal guaranteed! We specialize in sale pu...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Security / Fire..."
1431,"4 BHK Flatin Sector 72, Gurgaon",4.0,tata primanti,5.40,18588.64,2905.0,2200.0,4,5,servant room,"Tata Primanti Sector 72, Gurgaon",14,north-east,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This beautiful 4 bhk flat in sector 72 gurgaon...,"['4 Wardrobe', '1 Water Purifier', '8 Fan', '1...","['Centrally Air Conditioned', 'Water purifier'..."

In [93]:
dt.shape

(2149, 18)

In [97]:
dt.to_csv('gurgaon-flats-cleaned-v1.csv',index = False)